export default {
  SYMBOL_COLON: "SymbolColon",

  WELCOME_TITLE: "WelcomeTitle",
  HELLO: "Hello",
  NAME: "Name",
  PORTFOLIO_TITLE: "PortfolioTitle",
  PORTFOLIO_DESCRIPTION: "PortfolioDescription",

  PERSONALIZED: "Personalized",
  PERSONALIZED_DESCRIPTION: "PersonalizedDescription",
  PROFESSIONAL: "Professional",
  PROFESSIONAL_DESCRIPTION: "ProfessionalDescription",
  QUALITY: "Quality",
  QUALITY_DESCRIPTION: "QualityDescription",
  UNIQUE: "Unique",
  UNIQUE_DESCRIPTION: "UniqueDescription",

  SFXEXPLENAION: "SfxExplenation",
  SFXEXPLENAION_DESCRIPTION: "SfxExplenationDescription",

  CATEGORIES: "Categories",
  CATEGORIES_EFFECTS: "CategoriesEffects",
  CATEGORIES_DESCRIPTION: "CategoriesDescription",

  CONTACT_ME: "ContactMe",
  EMAIL: "Email",
  INSTA: "Insta",

  LIGHT: "Light",
  LIGHT_DESCRIPTION: "LightDescription",
  LIGHT_FEATURES: "LightFeatures",
  LIGHT_FEATURES_BLOOD: "LightFeaturesBlood",
  LIGHT_FEATURES_BLOOD_DESCRIPTION: "LightFeaturesBloodDescription",
  LIGHT_FEATURES_PAINT: "LightFeaturesPaint",
  LIGHT_FEATURES_PAINT_DESCRIPTION: "LightFeaturesPaintDescription",
  LIGHT_FEATURES_DECORATION: "LightFeaturesdecoration",
  LIGHT_FEATURES_DECORATION_DESCRIPTION: "LightFeaturesdecorationDescription",
  LIGHT_FOR: "LightFor",
  LIGHT_FOR_LIST: "LightForList",
  LIGHT_FOR_CONCLUSION: "LightForConclusion",
  LIGHT_THEME_EXAMPLES: "LightThemeExamples",
  LIGHT_THEME_EXAMPLES_LIST: "LightThemeExamplesList",

  MODERATE: "Moderate",
  MODERATE_DESCRIPTION: "ModerateDescription",
  MODERATE_FEATURES: "ModerateFeatures",
  MODERATE_FEATURES_BLOOD: "ModerateFeaturesBlood",
  MODERATE_FEATURES_BLOOD_DESCRIPTION: "ModerateFeaturesBloodDescription",
  MODERATE_FEATURES_PAINT: "ModerateFeaturesPaint",
  MODERATE_FEATURES_PAINT_DESCRIPTION: "ModerateFeaturesPaintDescription",
  MODERATE_FEATURES_DECORATION: "ModerateFeaturesdecoration",
  MODERATE_FEATURES_DECORATION_DESCRIPTION: "ModerateFeaturesdecorationDescription",
  MODERATE_FOR: "ModerateFor",
  MODERATE_FOR_LIST: "ModerateForList",
  MODERATE_FOR_CONCLUSION: "ModerateForConclusion",
  MODERATE_THEME_EXAMPLES: "ModerateThemeExamples",
  MODERATE_THEME_EXAMPLES_LIST: "ModerateThemeExamplesList",
}